import Link from "next/link";
import { FileText, ReceiptText, CircleDollarSign, Clock3, Plus } from "lucide-react";
import { Card } from "@/components/ui";
import { PageHeader } from "@/components/page-header";
import { getDocuments } from "@/lib/data";
import { formatMoney } from "@/lib/money";
import { humanizeStatus } from "@/lib/utils";

export default async function DashboardPage(){
  const docs=await getDocuments();const quotations=docs.filter(d=>d.document_type==="quotation");const invoices=docs.filter(d=>d.document_type==="invoice");const openQuotes=quotations.filter(d=>["draft","sent"].includes(d.status)).length;const unpaid=invoices.filter(d=>["unpaid","overdue"].includes(d.status)).length;const paid=invoices.filter(d=>d.status==="paid").length;const recent=docs.slice(0,6);
  const stats=[{label:"Total quotations",value:quotations.length,Icon:FileText},{label:"Open quotations",value:openQuotes,Icon:Clock3},{label:"Total invoices",value:invoices.length,Icon:ReceiptText},{label:"Unpaid invoices",value:unpaid,Icon:CircleDollarSign},{label:"Paid invoices",value:paid,Icon:CircleDollarSign}];
  return <><PageHeader title="Dashboard" description="Your billing activity at a glance." actions={<><Link className="btn btn-secondary" href="/quotations/new"><Plus size={16}/>New quotation</Link><Link className="btn btn-primary" href="/invoices/new"><Plus size={16}/>New invoice</Link></>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map(({label,value,Icon})=><Card key={label}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{label}</p><p className="mt-3 text-3xl font-black money">{value}</p></div><div className="rounded-lg bg-slate-100 p-2 text-[var(--navy)]"><Icon size={19}/></div></div></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1fr_300px]"><Card className="p-0"><div className="border-b border-[var(--rule)] p-5"><h2 className="font-black">Recent documents</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="bg-[#faf9f6] text-left text-[11px] uppercase tracking-wider text-[var(--muted)]"><th className="p-3">Number</th><th className="p-3">Customer</th><th className="p-3">Type</th><th className="p-3">Status</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{recent.length===0?<tr><td colSpan={5} className="p-8 text-center text-[var(--muted)]">No documents yet. Create your first quotation or invoice.</td></tr>:recent.map(d=>{const base=d.document_type==="quotation"?"quotations":"invoices";return <tr key={d.id} className="border-t border-[#eeeae3]"><td className="p-3"><Link className="font-bold hover:underline" href={`/${base}/${d.id}`}>{d.document_number}</Link></td><td className="p-3">{d.customer_snapshot?.name??"—"}</td><td className="p-3 capitalize">{d.document_type}</td><td className="p-3">{humanizeStatus(d.status)}</td><td className="p-3 text-right font-bold money">{formatMoney(d.grand_total,d.currency)}</td></tr>})}</tbody></table></div></Card><Card><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Quick setup</p><p className="mt-3 text-lg font-black">Keep billing details ready</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Add customers and reusable services first, then create documents faster with fewer repeated fields.</p><div className="mt-5 grid gap-2 border-t border-[var(--rule)] pt-4"><Link className="text-sm font-bold text-[var(--navy)] underline" href="/customers">Manage customers</Link><Link className="text-sm font-bold text-[var(--navy)] underline" href="/items">Manage items / services</Link><Link className="text-sm font-bold text-[var(--navy)] underline" href="/settings">Company settings</Link></div></Card></div></>;
}
