"use client";

import { useMemo, useState, useTransition, type FormEvent } from "react";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { deleteCustomer, saveCustomer } from "@/actions/customers";
import { useToast } from "@/components/toast";
import { Button, ConfirmDialog, Input, Label, Modal, Textarea } from "@/components/ui";
import type { Customer } from "@/lib/types";

export function CustomerManager({ customers }: { customers: Customer[] }) {
  const [query,setQuery]=useState(""); const [editing,setEditing]=useState<Customer|null>(null); const [open,setOpen]=useState(false); const [deleting,setDeleting]=useState<Customer|null>(null); const [pending,startTransition]=useTransition(); const {show}=useToast();
  const filtered=useMemo(()=>customers.filter(c=>`${c.name} ${c.email??""} ${c.phone??""}`.toLowerCase().includes(query.toLowerCase())),[customers,query]);
  function begin(customer?:Customer){ setEditing(customer??null); setOpen(true); }
  function submit(event:FormEvent<HTMLFormElement>){ event.preventDefault(); const fd=new FormData(event.currentTarget); const input={ id:editing?.id, name:String(fd.get("name")??""), contact_person:String(fd.get("contact_person")??""), phone:String(fd.get("phone")??""), email:String(fd.get("email")??""), billing_address:String(fd.get("billing_address")??""), tax_number:String(fd.get("tax_number")??""), notes:String(fd.get("notes")??"")}; startTransition(async()=>{ const res=await saveCustomer(input); if(!res.ok){show(res.error,"error");return;} show(editing?"Customer updated":"Customer created","success"); setOpen(false); }); }
  function confirmDelete(){ if(!deleting)return; startTransition(async()=>{const res=await deleteCustomer(deleting.id); if(!res.ok){show(res.error,"error");return;} show("Customer deleted; historical documents keep their snapshot.","success"); setDeleting(null);}); }
  return <>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers…" className="pl-9"/></div><Button type="button" onClick={()=>begin()}><Plus size={17}/>New customer</Button></div>
    <div className="grid gap-3 md:hidden">{filtered.length===0?<div className="rounded-xl border border-[var(--rule)] bg-white p-6 text-center text-sm text-[var(--muted)]">No customers found.</div>:filtered.map(c=><article key={c.id} className="rounded-xl border border-[var(--rule)] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-black">{c.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{c.billing_address||"No billing address"}</p></div><div className="flex shrink-0 gap-1"><button type="button" className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>begin(c)} aria-label="Edit"><Pencil size={16}/></button><button type="button" className="rounded-lg p-2 text-red-700 hover:bg-red-50" onClick={()=>setDeleting(c)} aria-label="Delete"><Trash2 size={16}/></button></div></div><div className="mt-3 border-t border-slate-100 pt-3 text-sm"><p className="font-semibold">{c.contact_person||"—"}</p><p className="mt-1 break-all text-xs text-[var(--muted)]">{c.email||c.phone||"—"}</p>{c.tax_number&&<p className="mt-2 text-xs"><span className="text-[var(--muted)]">Tax/VAT:</span> {c.tax_number}</p>}</div></article>)}</div>
    <div className="table-wrap hidden md:block"><table className="data-table"><thead><tr><th>Customer</th><th>Contact</th><th>Tax / VAT</th><th className="w-28">Actions</th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan={4} className="text-center text-[var(--muted)]">No customers found.</td></tr>:filtered.map(c=><tr key={c.id}><td><div className="font-bold">{c.name}</div><div className="mt-1 text-xs text-[var(--muted)]">{c.billing_address||"No billing address"}</div></td><td><div>{c.contact_person||"—"}</div><div className="text-xs text-[var(--muted)]">{c.email||c.phone||"—"}</div></td><td>{c.tax_number||"—"}</td><td><div className="flex gap-1"><button type="button" className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>begin(c)} aria-label="Edit"><Pencil size={16}/></button><button type="button" className="rounded-lg p-2 text-red-700 hover:bg-red-50" onClick={()=>setDeleting(c)} aria-label="Delete"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>
    <Modal open={open} title={editing?"Edit customer":"New customer"} onClose={()=>setOpen(false)}><form onSubmit={submit} className="grid gap-4"><div><Label>Customer / company name</Label><Input name="name" defaultValue={editing?.name??""} required/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Contact person</Label><Input name="contact_person" defaultValue={editing?.contact_person??""}/></div><div><Label>Tax / VAT number</Label><Input name="tax_number" defaultValue={editing?.tax_number??""}/></div><div><Label>Email</Label><Input name="email" type="email" defaultValue={editing?.email??""}/></div><div><Label>Phone</Label><Input name="phone" defaultValue={editing?.phone??""}/></div></div><div><Label>Billing address</Label><Textarea name="billing_address" defaultValue={editing?.billing_address??""}/></div><div><Label>Notes</Label><Textarea name="notes" defaultValue={editing?.notes??""}/></div><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={pending}>{pending?"Saving…":"Save customer"}</Button></div></form></Modal>
    <ConfirmDialog open={!!deleting} title="Delete customer?" message="The customer record will be removed. Existing quotations and invoices remain readable because they store a customer snapshot." onCancel={()=>setDeleting(null)} onConfirm={confirmDelete} busy={pending}/>
  </>;
}
