"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Copy, FileOutput, Pencil, Search, Trash2, Eye } from "lucide-react";
import { convertQuotation, deleteDocument, duplicateDocument } from "@/actions/documents";
import { DropdownMenu } from "@/components/dropdown-menu";
import { useToast } from "@/components/toast";
import { Badge, ConfirmDialog, Input, Select } from "@/components/ui";
import { formatMoney } from "@/lib/money";
import type { DocumentRecord, DocumentType } from "@/lib/types";
import { humanizeStatus } from "@/lib/utils";

function effectiveStatus(doc:DocumentRecord, today:string){if(doc.document_type==="invoice"&&doc.status==="unpaid"&&doc.due_date&&doc.due_date<today)return "overdue";return doc.status;}
function tone(status:string):"neutral"|"good"|"warn"|"bad"|"blue" {if(["paid","accepted"].includes(status))return "good";if(["overdue","rejected","cancelled"].includes(status))return "bad";if(["sent","unpaid"].includes(status))return "warn";if(status==="draft")return "neutral";return "blue";}

export function DocumentsTable({ documents, type, today }: { documents:DocumentRecord[]; type:DocumentType; today:string }) {
  const router=useRouter();const {show}=useToast();const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [sort,setSort]=useState("date-desc");const [deleting,setDeleting]=useState<DocumentRecord|null>(null);const [pending,startTransition]=useTransition();
  const base=type==="quotation"?"quotations":"invoices";
  const statuses=type==="quotation"?["draft","sent","accepted","rejected","expired"]:["draft","unpaid","paid","overdue","cancelled"];
  const rows=useMemo(()=>documents.filter(d=>{const snapshot=d.customer_snapshot;const match=`${d.document_number} ${snapshot?.name??""}`.toLowerCase().includes(query.toLowerCase());return match&&(status==="all"||effectiveStatus(d,today)===status);}).sort((a,b)=>{if(sort==="date-asc")return a.issue_date.localeCompare(b.issue_date);if(sort==="amount-desc")return Number(b.grand_total)-Number(a.grand_total);if(sort==="amount-asc")return Number(a.grand_total)-Number(b.grand_total);if(sort==="number")return a.document_number.localeCompare(b.document_number);return b.issue_date.localeCompare(a.issue_date);}),[documents,query,status,sort,today]);
  function duplicate(doc:DocumentRecord){startTransition(async()=>{const r=await duplicateDocument(doc.id);if(!r.ok){show(r.error,"error");return;}show("Duplicate created","success");router.push(`/${base}/${r.id}/edit`);});}
  function convert(doc:DocumentRecord){startTransition(async()=>{const r=await convertQuotation(doc.id);if(!r.ok){show(r.error,"error");return;}show(r.alreadyExisted?"Already converted; opening the existing invoice.":"Invoice created","success");router.push(`/invoices/${r.id}`);});}
  function remove(){if(!deleting)return;startTransition(async()=>{const r=await deleteDocument(deleting.id);if(!r.ok){show(r.error,"error");return;}show("Document deleted","success");setDeleting(null);router.refresh();});}
  return <><div className="mb-4 grid gap-3 md:grid-cols-[minmax(240px,1fr)_180px_180px]"><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${base}…`}/></div><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{humanizeStatus(s)}</option>)}</Select><Select value={sort} onChange={e=>setSort(e.target.value)}><option value="date-desc">Newest first</option><option value="date-asc">Oldest first</option><option value="amount-desc">Amount: high to low</option><option value="amount-asc">Amount: low to high</option><option value="number">Document number</option></Select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Document</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th><th className="w-16"></th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="text-center text-[var(--muted)]">No {base} found.</td></tr>:rows.map(doc=><tr key={doc.id}><td><Link href={`/${base}/${doc.id}`} className="font-black text-[var(--navy)] hover:underline">{doc.document_number}</Link></td><td>{doc.customer_snapshot?.name??"—"}</td><td>{doc.issue_date}</td><td className="font-bold money">{formatMoney(doc.grand_total,doc.currency)}</td><td><Badge tone={tone(effectiveStatus(doc,today))}>{humanizeStatus(effectiveStatus(doc,today))}</Badge></td><td><DropdownMenu items={[{label:"View",icon:<Eye size={15}/>,onClick:()=>router.push(`/${base}/${doc.id}`)},{label:"Edit",icon:<Pencil size={15}/>,onClick:()=>router.push(`/${base}/${doc.id}/edit`)},{label:"Duplicate",icon:<Copy size={15}/>,onClick:()=>duplicate(doc),disabled:pending},...(type==="quotation"?[{label:"Convert to invoice",icon:<FileOutput size={15}/>,onClick:()=>convert(doc),disabled:pending}]:[]),{label:"Delete",icon:<Trash2 size={15}/>,onClick:()=>setDeleting(doc),danger:true}]} /></td></tr>)}</tbody></table></div><ConfirmDialog open={!!deleting} title={`Delete ${deleting?.document_number??"document"}?`} message="This permanently deletes the document and its line items." onCancel={()=>setDeleting(null)} onConfirm={remove} busy={pending}/></>;
}
